// <auto-generated />
using GestionNotas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionNotas.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929193000_NotaUnica")]
    partial class NotaUnica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionNotas.Domain.Entities.Estudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Estudiante");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Estudiante_Nombre");

                    b.ToTable("Estudiante", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Sofía Ramírez"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Santiago Gómez"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Valentina Muñoz"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Mateo Rojas"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Isabella Díaz"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Samuel Torres"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Mariana Vargas"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Sebastián Peña"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Camila Ortiz"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Nicolás Jiménez"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Daniela Ríos"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Tomás Álvarez"
                        });
                });

            modelBuilder.Entity("GestionNotas.Domain.Entities.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.Property<int>("IdProfesor")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.HasKey("Id")
                        .HasName("PK_Nota");

                    b.HasIndex("IdEstudiante")
                        .HasDatabaseName("IX_Nota_IdEstudiante");

                    b.HasIndex("IdEstudiante", "IdProfesor", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Nota_IdEstudiante_IdProfesor_Nombre");

                    b.HasIndex("IdProfesor")
                        .HasDatabaseName("IX_Nota_IdProfesor");

                    b.ToTable("Nota", null, t =>
                        {
                            t.HasCheckConstraint("CK_Nota_Valor", "[Valor] >= 0 AND [Valor] <= 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdEstudiante = 1,
                            IdProfesor = 2,
                            Nombre = "Parcial 2",
                            Valor = 3.5m
                        },
                        new
                        {
                            Id = 2,
                            IdEstudiante = 1,
                            IdProfesor = 3,
                            Nombre = "Taller de álgebra",
                            Valor = 2.9m
                        },
                        new
                        {
                            Id = 3,
                            IdEstudiante = 1,
                            IdProfesor = 4,
                            Nombre = "Quiz de programación",
                            Valor = 3.8m
                        },
                        new
                        {
                            Id = 4,
                            IdEstudiante = 2,
                            IdProfesor = 3,
                            Nombre = "Taller de álgebra",
                            Valor = 4.7m
                        },
                        new
                        {
                            Id = 5,
                            IdEstudiante = 2,
                            IdProfesor = 4,
                            Nombre = "Quiz de programación",
                            Valor = 1.8m
                        },
                        new
                        {
                            Id = 6,
                            IdEstudiante = 2,
                            IdProfesor = 5,
                            Nombre = "Examen final",
                            Valor = 2.4m
                        },
                        new
                        {
                            Id = 7,
                            IdEstudiante = 3,
                            IdProfesor = 4,
                            Nombre = "Quiz de programación",
                            Valor = 4.2m
                        },
                        new
                        {
                            Id = 8,
                            IdEstudiante = 3,
                            IdProfesor = 5,
                            Nombre = "Examen final",
                            Valor = 2.4m
                        },
                        new
                        {
                            Id = 9,
                            IdEstudiante = 3,
                            IdProfesor = 1,
                            Nombre = "Exposición",
                            Valor = 3.5m
                        },
                        new
                        {
                            Id = 10,
                            IdEstudiante = 4,
                            IdProfesor = 5,
                            Nombre = "Examen final",
                            Valor = 4.5m
                        },
                        new
                        {
                            Id = 11,
                            IdEstudiante = 4,
                            IdProfesor = 1,
                            Nombre = "Exposición",
                            Valor = 1.8m
                        },
                        new
                        {
                            Id = 12,
                            IdEstudiante = 4,
                            IdProfesor = 2,
                            Nombre = "Proyecto integrador",
                            Valor = 4.2m
                        },
                        new
                        {
                            Id = 13,
                            IdEstudiante = 5,
                            IdProfesor = 1,
                            Nombre = "Exposición",
                            Valor = 3.0m
                        },
                        new
                        {
                            Id = 14,
                            IdEstudiante = 5,
                            IdProfesor = 2,
                            Nombre = "Proyecto integrador",
                            Valor = 1.8m
                        },
                        new
                        {
                            Id = 15,
                            IdEstudiante = 5,
                            IdProfesor = 3,
                            Nombre = "Parcial 1",
                            Valor = 2.4m
                        },
                        new
                        {
                            Id = 16,
                            IdEstudiante = 6,
                            IdProfesor = 2,
                            Nombre = "Proyecto integrador",
                            Valor = 3.8m
                        },
                        new
                        {
                            Id = 17,
                            IdEstudiante = 6,
                            IdProfesor = 3,
                            Nombre = "Parcial 1",
                            Valor = 3.8m
                        },
                        new
                        {
                            Id = 18,
                            IdEstudiante = 6,
                            IdProfesor = 4,
                            Nombre = "Parcial 2",
                            Valor = 2.4m
                        },
                        new
                        {
                            Id = 19,
                            IdEstudiante = 7,
                            IdProfesor = 3,
                            Nombre = "Parcial 1",
                            Valor = 3.0m
                        },
                        new
                        {
                            Id = 20,
                            IdEstudiante = 7,
                            IdProfesor = 4,
                            Nombre = "Parcial 2",
                            Valor = 2.4m
                        },
                        new
                        {
                            Id = 21,
                            IdEstudiante = 8,
                            IdProfesor = 4,
                            Nombre = "Parcial 2",
                            Valor = 4.2m
                        },
                        new
                        {
                            Id = 22,
                            IdEstudiante = 8,
                            IdProfesor = 5,
                            Nombre = "Taller de álgebra",
                            Valor = 3.8m
                        },
                        new
                        {
                            Id = 23,
                            IdEstudiante = 9,
                            IdProfesor = 5,
                            Nombre = "Taller de álgebra",
                            Valor = 1.8m
                        },
                        new
                        {
                            Id = 24,
                            IdEstudiante = 9,
                            IdProfesor = 1,
                            Nombre = "Quiz de programación",
                            Valor = 4.5m
                        },
                        new
                        {
                            Id = 25,
                            IdEstudiante = 10,
                            IdProfesor = 1,
                            Nombre = "Quiz de programación",
                            Valor = 2.4m
                        },
                        new
                        {
                            Id = 26,
                            IdEstudiante = 10,
                            IdProfesor = 2,
                            Nombre = "Examen final",
                            Valor = 3.0m
                        },
                        new
                        {
                            Id = 27,
                            IdEstudiante = 11,
                            IdProfesor = 2,
                            Nombre = "Examen final",
                            Valor = 4.7m
                        },
                        new
                        {
                            Id = 28,
                            IdEstudiante = 11,
                            IdProfesor = 3,
                            Nombre = "Exposición",
                            Valor = 4.7m
                        });
                });

            modelBuilder.Entity("GestionNotas.Domain.Entities.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Profesor");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Profesor_Nombre");

                    b.ToTable("Profesor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Carlos Rodríguez"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "María Fernanda López"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Jorge Iván Martínez"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Ana Lucía Herrera"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Andrés Felipe Castaño"
                        });
                });

            modelBuilder.Entity("GestionNotas.Domain.Entities.Nota", b =>
                {
                    b.HasOne("GestionNotas.Domain.Entities.Estudiante", "Estudiante")
                        .WithMany("Notas")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Nota_Estudiante");

                    b.HasOne("GestionNotas.Domain.Entities.Profesor", "Profesor")
                        .WithMany("Notas")
                        .HasForeignKey("IdProfesor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Nota_Profesor");

                    b.Navigation("Estudiante");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("GestionNotas.Domain.Entities.Estudiante", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("GestionNotas.Domain.Entities.Profesor", b =>
                {
                    b.Navigation("Notas");
                });
#pragma warning restore 612, 618
        }
    }
}
